# Jman's tmux conf

set-option -g history-limit 100000                                                                                                                                                                                 
#Enable mouse support in ~/.tmux.conf
#set-option -g mouse-select-pane on
#set-option -g mouse-select-window on
#set-window-option -g mode-mouse on

set -g prefix2 `
bind ` send-prefix -2

bind r source-file ~/.tmux.conf; display-message "Config reloaded..";

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Alt j and k to switch windows
bind -n M-j next-window
bind -n M-k previous-window

# Otherwise the windows keep inheriting the folder name
set-option -g allow-rename off

# Make tmux pass all special keys to vim
set-window-option -g xterm-keys on

# Bindings to simplify backing scrollback
bind b capture-pane -S -100000 -E 45 \; save-buffer -a /home/jman/tmux-scrollback \; next-window

# Fix ncurses - Curses!
set -g default-terminal "screen"

# Set current active window status colour
set-window-option -g window-status-current-bg cyan

# Colours for vim style selection in copy mode
set-window-option -g mode-style fg=white,bg=green

